# Generated by Django 5.1.6 on 2025-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_password', models.CharField(blank=True, max_length=100, null=True)),
                ('plant', models.JSONField()),
                ('predicted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelpredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255, null=True)),
                ('image', models.TextField(max_length=100000000000000000)),
                ('predict_class', models.TextField(default='', max_length=100)),
                ('predict_accuracy', models.IntegerField(default=0)),
                ('predicted', models.BooleanField(default=False)),
            ],
        ),
    ]
