# Generated by Django 5.1.5 on 2025-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpredict',
            name='predict_accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
