# Generated by Django 5.1.5 on 2025-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_modelpredict_predict_accuracy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpredict",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
