# Generated by Django 5.1.5 on 2025-02-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_modelpredict_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="esp32_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="esp32_images/"),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                (
                    "predict_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("predict_accuracy", models.IntegerField(blank=True, null=True)),
                ("predicted", models.BooleanField(default=False)),
            ],
        ),
    ]
