# Generated by Django 5.1.5 on 2025-03-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_esp32_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpredict",
            name="image",
            field=models.TextField(max_length=100000000000000000),
        ),
    ]
