# Generated by Django 5.1.5 on 2025-03-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_modelpredict_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esp32_data",
            name="image",
            field=models.ImageField(default="", upload_to="esp32_images/"),
        ),
    ]
