# Generated by Django 5.1.6 on 2025-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_esp32_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32_data',
            name='image',
            field=models.TextField(max_length=100000000000000000),
        ),
    ]
