# Generated by Django 5.1.6 on 2025-04-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_esp32_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpredict',
            name='image_id',
            field=models.CharField(default='no_id', max_length=100),
        ),
    ]
