# Generated by Django 5.1.6 on 2025-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_modelpredict_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpredict',
            name='predict_class',
            field=models.TextField(default='', max_length=100),
        ),
    ]
