# Generated by Django 5.1.6 on 2025-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_modelpredict_predict_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpredict',
            name='image_id',
            field=models.IntegerField(default=0),
        ),
    ]
