# Generated by Django 5.1.6 on 2025-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_modelpredict_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpredict',
            name='image_id',
            field=models.CharField(default='no_id', max_length=100),
        ),
    ]
